
# Dictionary containing the the name of the country as a value and the
#... associated elo and one_year_change in elo of the country

elo_ratings_dict = {
        "canada" : {"elo" : 1784 ,"one_year_change" : 6},
        "usa"    : {"elo" : 1733 , "one_year_change" : 11},
        "mexico" : {"elo" : 1868 , "one_year_change" : 51},
        "algeria": {"elo" : 1743 , "one_year_change" : 35},
        "argentina" : {"elo": 2113 , "one_year_change" : -28},
        "australia" : {"elo" : 1775 , "one_year_change" : 38},
        "austria"  : {"elo" : 1827 ,"one_year_change" : -10},
        "belgium" : {"elo" : 1867 , "one_year_change" : 23},
        "bosnia" : {"elo" : 1591  , "one_year_change" : 65},
        "brazil" : {"elo" : 1988 , "one_year_change" : -5},
        "caboverde" : {"elo" : 1576 , "one_year_change" : 76},
        "colombia"  : {"elo" : 1975 , "one_year_change" : 24},
        "congo_dr"  : {"elo" : 1655 , "one_year_change" : 89},
        "ivory_coast" : {"elo" : 1676 , "one_year_change": 85},
        "croatia"   : {"elo" :1930 , "one_year_change": 19},
        "curacao": {"elo" : 1433 , "one_year_change" : 110},
        "czechia" : {"elo" : 1733 , "one_year_change" : -22},
        "ecuador" : {"elo": 1953  , "one_year_change" : 24},
        "egypt"   : {"elo" : 1699 , "one_year_change" : 33},
        "england" : {"elo" : 2020 , "one_year_change" : 9},
        "france"  :{"elo" : 2081  , "one_year_change" : 51},
        "germany" :{"elo" : 1925  , "one_year_change" : -62},
        "ghana"   :{"elo" : 1503 , "one_year_change" : 26},
        "haiti"   :{"elo": 1532 , "one_year_change" : -21},
        "iran"     :{"elo": 1764 , "one_year_change" : -66},
        "iraq"     :{"elo": 1608 , "one_year_change" : 69},
        "japan"    :{"elo": 1906 , "one_year_change" : -30},
        "jordan"   :{"elo": 1685 , "one_year_change" : 66},
        "korea"   :{"elo": 1756 , "one_year_change" : 10},
        "morocco"    :{"elo": 1822 , "one_year_change" : 16},
        "netherlands" :{"elo": 1961 , "one_year_change" : -5},
        "newzealand"  :{"elo": 1585 , "one_year_change" : -10},
        "norway"   :{"elo": 1912, "one_year_change" : 83},
        "panama"   :{"elo": 1733 , "one_year_change" : 10},
        "paraguay"  :{"elo": 1833 , "one_year_change" : 33},
        "portugal"  :{"elo": 1984 , "one_year_change" : -4},
        "qatar"  :{"elo": 1423 , "one_year_change" : -75},
        "saudi"   :{"elo": 1566 , "one_year_change" : -10},
        "scotland"  :{"elo": 1770 , "one_year_change" : 28},
        "senegal"   :{"elo": 1866 , "one_year_change" : 107},
        "south_africa"   :{"elo": 1517 , "one_year_change" : -81},
        "spain"  :{"elo": 2165, "one_year_change" : 15},
        "sweden"  :{"elo": 1719 , "one_year_change" : -17},
        "switzerland"  :{"elo": 1894 , "one_year_change" : 82},
        "tunisia"  :{"elo": 1636 , "one_year_change" : 25},
        "turkey"  :{"elo": 1902 , "one_year_change" : 65},
        "uruguay"  :{"elo": 1892 , "one_year_change" : -29},
        "uzbekistan"  :{"elo": 1727 , "one_year_change" : 30},
        }